const record=await(await fetch('../provenance.json')).json(),rev=record.source.commit;
const {createBakery}=await import(`../source/${rev}/src/pies.js`);
const canvas=document.querySelector('#bakery');const bakery=createBakery(canvas);let states=[{n:1,d:2},{n:2,d:4}],drawer=false,top=false,busy=false;
const status=document.querySelector('#status');const setStatus=text=>status.textContent=text;
function update(){bakery.update(...states);setStatus(`Pie A: ${states[0].n}/${states[0].d}. Pie B: ${states[1].n}/${states[1].d}.`);document.querySelector('#cut').disabled=busy||states[0].d>=16;document.querySelector('#regroup').disabled=busy||states[0].d<=2||states[0].n%2!==0}
function preset(name){if(busy)return;const values={halves:[[1,2],[2,4]],quarters:[[3,4],[6,8]],sixteenths:[[8,16],[4,8]],zero:[[0,4],[4,4]]};states=values[name].map(([n,d])=>({n,d}));bakery.emphasize(null);bakery.setFeedback('A',null);bakery.setFeedback('B',null);update()}
async function transform(type){if(busy||type==='cut'&&states[0].d>=16||type==='regroup'&&(states[0].d<=2||states[0].n%2))return;busy=true;document.querySelectorAll('button').forEach(b=>b.disabled=true);const from={...states[0]},factor=type==='cut'?2:.5,to={n:from.n*factor,d:from.d*factor};setStatus(`${type==='cut'?'Cutting':'Regrouping'} Pie A — Same Amount`);await bakery.transform('A',type,from,to);states[0]=to;busy=false;document.querySelectorAll('button').forEach(b=>b.disabled=false);update()}
function tone(value){bakery.emphasize(null);bakery.setFeedback('A',null);if(value==='focus'){bakery.emphasize({pair:'A',k:1});setStatus('Focus: Piece 1 Of Pie A — Dashed Outline; Amount Unchanged')}else if(value==='correct'||value==='incorrect'){bakery.setFeedback('A',value);setStatus(value==='correct'?'Correct — Green Serving Border And Selected Berries':'Not Yet — Red Serving Border And Selected Berries')}else setStatus('Selected Serving — Purple Outline; Amount Unchanged')}
document.querySelectorAll('[data-preset]').forEach(b=>b.addEventListener('click',()=>preset(b.dataset.preset)));document.querySelectorAll('[data-tone]').forEach(b=>b.addEventListener('click',()=>tone(b.dataset.tone)));
document.querySelector('#drawer').onclick=e=>{drawer=!drawer;bakery.setDrawer(drawer);e.target.textContent=drawer?'Close Drawer':'Open Drawer'};
document.querySelector('#top').onclick=e=>{top=!top;bakery.setTopView(top);e.target.textContent=top?'Perspective View':'Top View'};
document.querySelector('#orbit-left').onclick=()=>bakery.orbit(-.1);document.querySelector('#orbit-right').onclick=()=>bakery.orbit(.1);document.querySelector('#cut').onclick=()=>transform('cut');document.querySelector('#regroup').onclick=()=>transform('regroup');
document.querySelector('#identity').textContent=`Live Source Asset Demo — Not A New Game Build Or GLB Export. Source: ${record.source.repository}@${rev}. Upstream build reference: ${record.upstreamBuild.id}. Three.js 0.186.1 (MIT). Teacher visual acceptance pending.`;
console.info('Live Source Asset Demo',record.source.commit,record.upstreamBuild.id);
window.assetDemo={bakery,preset,transform,tone,get states(){return states},get busy(){return busy},sourceRevision:rev,buildId:record.upstreamBuild.id};update();window.demoReady=true;
